# Dependencies
markdown:           redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments:           true

# Permalinks
permalink:          pretty

# Server
host:               0.0.0.0
port:               9001
baseurl:            /
url:                http://localhost:9001
encoding:           UTF-8

# the excluded directoies
exclude:            []

# site information
info:
  site_name:        BinPack

meta:
  description:      "Json like, small and most fast."
  keywords:         "binpack, binary serialize, binary deserialize"
  author:           "liaohuqiu@gmail.com"

# multiple language
language_default:   'en'

languages:          ["en", "cn"]

# left navigation
left_nav:
  en:
    title:          BinPack
    path:           /
    items1:
      - path:       /page1
        title:      "Another page"
      - path:       /page2
        title:      "Yet another page"

# right navigation
right_nav:
  - title:          Fork on Github
    url:            https://github.com/binpack/binpack

# analytics account information, remember to change this.
analytics:
  google:
    account:         UA-43024238-6
